ARQUIVO_TREINO = './data/mnist_train.csv'
ARQUIVO_TESTE = './data/mnist_test.csv'

SEMENTE = 1

AG_POPULACAO = 50
AG_GERACOES = 100
AG_TAXA_CRUZAMENTO = 0.8
AG_TAXA_MUTACAO = 0.01
AG_TAMANHO_TORNEIO = 3
AG_TAXA_ELITISMO = 0.1
AG_PESO_ACURACIA = 0.7
AG_PESO_CARACTERISTICAS = 0.3
AG_PARADA_SEM_MELHORIA = 50

WRAPPER_MAX_ITERACOES = 100
WRAPPER_PARADA_SEM_MELHORIA = 20

PROPORCAO_VALIDACAO = 0.2
